Resources:
  NginxEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref NginxInstanceAMI
      InstanceType: !Ref NginxInstanceType
      KeyName: !Ref NginxInstanceKeyPair
      IamInstanceProfile: !Ref NginxEC2IAMInstanceProfile
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !GetAtt SecurityGroup.GroupId
          SubnetId: !Ref Subnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex

          sudo su -

          add-apt-repository ppa:maxmind/ppa
          apt-get update
          apt-get install -y nginx libnginx-mod-http-geoip2 geoipupdate openjdk-8-jdk ant ant-optional
          apt-get remove -y openjdk-11-jre-headless

          ##
          # Nginx
          ##

          cat << EOF > /etc/nginx/sites-available/default
          geoip2 /usr/share/maxmind/GeoLite2-Country.mmdb {
            auto_reload 30m;
            \$geoip2_data_country_code country iso_code;
          }

          geoip2 /usr/share/maxmind/GeoLite2-City.mmdb {
            auto_reload 30m;
            \$geoip2_data_city_name city names en;
          }

          log_format geolog escape=json '["\$remote_addr","\$geoip2_data_country_code","\$geoip2_data_city_name","\$request","\$args"]';

          server {
            server_name _;

            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;
            access_log /var/log/nginx/access.log geolog buffer=32k flush=5s;

            location / {
              return 204;
            }
          }
          EOF

          ##
          # MaxMind Autoupdates
          ##

          mkdir /etc/maxmind
          mkdir /usr/share/maxmind

          cat << EOF > /etc/maxmind/GeoIP.conf
          AccountID ${MaxmindAccountID}
          LicenseKey ${MaxmindLicenseKey}
          EditionIDs GeoLite2-ASN GeoLite2-City GeoLite2-Country
          DatabaseDirectory /usr/share/maxmind
          EOF

          geoipupdate -f /etc/maxmind/GeoIP.conf

          ##
          # AWS Kinesis Agent
          ##

          wget -qO- https://github.com/awslabs/amazon-kinesis-agent/archive/2.0.1.tar.gz | tar -zx --directory=/opt
          pushd /opt/amazon-kinesis-agent-2.0.1
          ./setup --install
          popd

          cat << EOF > /etc/aws-kinesis/agent.json
          {
            "cloudwatch.emitMetrics": false,
            "kinesis.endpoint": "",
            "firehose.endpoint": "firehose.${AWS::Region}.amazonaws.com",
            "flows": [
              {
                "filePattern": "/var/log/nginx/access.log",
                "deliveryStream": "${AWS::StackName}"
              }
            ]
          }
          EOF

          service nginx restart
          service aws-kinesis-agent restart

          chmod 0755 /var/log/nginx/access.log
